actuals_query = """
SELECT * FROM DEPT_FINANCE.PUBLIC.BENS_PL_ACTUALS
"""

budget_query = """
SELECT * FROM DEPT_FINANCE.PUBLIC.BENS_PL_BUDGET
"""

all_query = """
SELECT * FROM DEPT_FINANCE.PUBLIC.BENS_PL_V4 LIMIT 10000;
"""