actuals_query = """
    SELECT * FROM DEPT_FINANCE.PUBLIC.BENS_PL_ACTUALS
"""

budget_query = """
    SELECT * FROM DEPT_FINANCE.PUBLIC.BENS_PL_BUDGET
"""

all_query = """
    SELECT * FROM DEPT_FINANCE.PUBLIC.BENS_PL_V4 LIMIT 10000;
"""

KMX_query = """
    SELECT * FROM DEPT_FINANCE.PUBLIC.KMX_PRODUCT_SUMMARY
"""

###Master Lookup Queries###
Items_query = """
    SELECT * FROM DEPT_FINANCE.PUBLIC.BENS_MASTER_LOOKUP_ITEMS
"""
Consignors_query = """
    SELECT * FROM DEPT_FINANCE.PUBLIC.BENS_MASTER_LOOKUP_CONSIGNORS
"""
Partners_query = """
    SELECT * FROM DEPT_FINANCE.PUBLIC.BENS_MASTER_LOOKUP_PARTNERS
"""
Departments_query = """
    SELECT * FROM DEPT_FINANCE.PUBLIC.BENS_MASTER_LOOKUP_DEPARTMENTS
"""
Customers_query = """
    SELECT * FROM DEPT_FINANCE.PUBLIC.BENS_MASTER_LOOKUP_CUSTOMERS
"""
Employees_query = """
    SELECT * FROM DEPT_FINANCE.PUBLIC.BENS_MASTER_LOOKUP_EMPLOYEES
"""
Discounts_query = """
    SELECT * FROM DEPT_FINANCE.PUBLIC.BENS_MASTER_LOOKUP_DISCOUNTS
"""

####VINs Query####

VINs_query = """
    SELECT * FROM DEPT_FINANCE.PUBLIC.VINS_TO_ONESTREAM
"""

